--------------------------------------------------------
--  File created - sábado-mayo-04-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUTH_GROUP
--------------------------------------------------------

  CREATE TABLE "C##PRUEBA"."AUTH_GROUP" 
   (	"ID" NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" NVARCHAR2(150)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTH_GROUP_PERMISSIONS
--------------------------------------------------------

  CREATE TABLE "C##PRUEBA"."AUTH_GROUP_PERMISSIONS" 
   (	"ID" NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"GROUP_ID" NUMBER(11,0), 
	"PERMISSION_ID" NUMBER(11,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTH_PERMISSION
--------------------------------------------------------

  CREATE TABLE "C##PRUEBA"."AUTH_PERMISSION" 
   (	"ID" NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" NVARCHAR2(255), 
	"CONTENT_TYPE_ID" NUMBER(11,0), 
	"CODENAME" NVARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTHTOKEN_TOKEN
--------------------------------------------------------

  CREATE TABLE "C##PRUEBA"."AUTHTOKEN_TOKEN" 
   (	"KEY" NVARCHAR2(40), 
	"CREATED" TIMESTAMP (6), 
	"USER_ID" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTH_USER
--------------------------------------------------------

  CREATE TABLE "C##PRUEBA"."AUTH_USER" 
   (	"ID" NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PASSWORD" NVARCHAR2(128), 
	"LAST_LOGIN" TIMESTAMP (6), 
	"IS_SUPERUSER" NUMBER(1,0), 
	"USERNAME" NVARCHAR2(150), 
	"FIRST_NAME" NVARCHAR2(150), 
	"LAST_NAME" NVARCHAR2(150), 
	"EMAIL" NVARCHAR2(254), 
	"IS_STAFF" NUMBER(1,0), 
	"IS_ACTIVE" NUMBER(1,0), 
	"DATE_JOINED" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTH_USER_GROUPS
--------------------------------------------------------

  CREATE TABLE "C##PRUEBA"."AUTH_USER_GROUPS" 
   (	"ID" NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER(11,0), 
	"GROUP_ID" NUMBER(11,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTH_USER_USER_PERMISSIONS
--------------------------------------------------------

  CREATE TABLE "C##PRUEBA"."AUTH_USER_USER_PERMISSIONS" 
   (	"ID" NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER(11,0), 
	"PERMISSION_ID" NUMBER(11,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DJANGO_ADMIN_LOG
--------------------------------------------------------

  CREATE TABLE "C##PRUEBA"."DJANGO_ADMIN_LOG" 
   (	"ID" NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ACTION_TIME" TIMESTAMP (6), 
	"OBJECT_ID" NCLOB, 
	"OBJECT_REPR" NVARCHAR2(200), 
	"ACTION_FLAG" NUMBER(11,0), 
	"CHANGE_MESSAGE" NCLOB, 
	"CONTENT_TYPE_ID" NUMBER(11,0), 
	"USER_ID" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("OBJECT_ID") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("CHANGE_MESSAGE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table DJANGO_CONTENT_TYPE
--------------------------------------------------------

  CREATE TABLE "C##PRUEBA"."DJANGO_CONTENT_TYPE" 
   (	"ID" NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"APP_LABEL" NVARCHAR2(100), 
	"MODEL" NVARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DJANGO_MIGRATIONS
--------------------------------------------------------

  CREATE TABLE "C##PRUEBA"."DJANGO_MIGRATIONS" 
   (	"ID" NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"APP" NVARCHAR2(255), 
	"NAME" NVARCHAR2(255), 
	"APPLIED" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DJANGO_SESSION
--------------------------------------------------------

  CREATE TABLE "C##PRUEBA"."DJANGO_SESSION" 
   (	"SESSION_KEY" NVARCHAR2(40), 
	"SESSION_DATA" NCLOB, 
	"EXPIRE_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("SESSION_DATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table MIAPP_MICUENTATF
--------------------------------------------------------

  CREATE TABLE "C##PRUEBA"."MIAPP_MICUENTATF" 
   (	"ID" NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TITLE" NVARCHAR2(200), 
	"DESCRIPTION" NCLOB, 
	"CREATED" TIMESTAMP (6), 
	"DATECOMPLETED" TIMESTAMP (6), 
	"IMPORTANT" NUMBER(1,0), 
	"USER_ID" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table MIAPP_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "C##PRUEBA"."MIAPP_PRODUCTO" 
   (	"CODIGO" NVARCHAR2(4), 
	"DETALLE" VARCHAR2(600 BYTE), 
	"PRECIO" NUMBER(11,0), 
	"STOCK" NUMBER(11,0), 
	"OFERTA" NUMBER(1,0), 
	"IMAGEN" NVARCHAR2(200), 
	"TIPO" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##PRUEBA.AUTH_GROUP
SET DEFINE OFF;
REM INSERTING into C##PRUEBA.AUTH_GROUP_PERMISSIONS
SET DEFINE OFF;
REM INSERTING into C##PRUEBA.AUTH_PERMISSION
SET DEFINE OFF;
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('1','Can add log entry','1','add_logentry');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('2','Can change log entry','1','change_logentry');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('3','Can delete log entry','1','delete_logentry');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('4','Can view log entry','1','view_logentry');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('5','Can add permission','2','add_permission');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('6','Can change permission','2','change_permission');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('7','Can delete permission','2','delete_permission');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('8','Can view permission','2','view_permission');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('9','Can add group','3','add_group');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('10','Can change group','3','change_group');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('11','Can delete group','3','delete_group');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('12','Can view group','3','view_group');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('13','Can add user','4','add_user');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('14','Can change user','4','change_user');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('15','Can delete user','4','delete_user');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('16','Can view user','4','view_user');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('17','Can add content type','5','add_contenttype');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('18','Can change content type','5','change_contenttype');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('19','Can delete content type','5','delete_contenttype');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('20','Can view content type','5','view_contenttype');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('21','Can add session','6','add_session');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('22','Can change session','6','change_session');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('23','Can delete session','6','delete_session');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('24','Can view session','6','view_session');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('25','Can add micuentatf','7','add_micuentatf');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('26','Can change micuentatf','7','change_micuentatf');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('27','Can delete micuentatf','7','delete_micuentatf');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('28','Can view micuentatf','7','view_micuentatf');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('29','Can add producto','8','add_producto');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('30','Can change producto','8','change_producto');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('31','Can delete producto','8','delete_producto');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('32','Can view producto','8','view_producto');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('41','Can add Token','21','add_token');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('42','Can change Token','21','change_token');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('43','Can delete Token','21','delete_token');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('44','Can view Token','21','view_token');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('45','Can add Token','22','add_tokenproxy');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('46','Can change Token','22','change_tokenproxy');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('47','Can delete Token','22','delete_tokenproxy');
Insert into C##PRUEBA.AUTH_PERMISSION (ID,NAME,CONTENT_TYPE_ID,CODENAME) values ('48','Can view Token','22','view_tokenproxy');
REM INSERTING into C##PRUEBA.AUTHTOKEN_TOKEN
SET DEFINE OFF;
Insert into C##PRUEBA.AUTHTOKEN_TOKEN (KEY,CREATED,USER_ID) values ('12d5b1eea3a3cfc59998a64eca30ecad7e9d6d9c',to_timestamp('22/04/24 13:24:24,446455000','DD/MM/RR HH24:MI:SSXFF'),'42');
Insert into C##PRUEBA.AUTHTOKEN_TOKEN (KEY,CREATED,USER_ID) values ('58775635c6674b257b652969d59d6178288ea596',to_timestamp('29/04/24 07:28:35,014409000','DD/MM/RR HH24:MI:SSXFF'),'3');
REM INSERTING into C##PRUEBA.AUTH_USER
SET DEFINE OFF;
Insert into C##PRUEBA.AUTH_USER (ID,PASSWORD,LAST_LOGIN,IS_SUPERUSER,USERNAME,FIRST_NAME,LAST_NAME,EMAIL,IS_STAFF,IS_ACTIVE,DATE_JOINED) values ('5','pbkdf2_sha256$600000$Zi66WGd2IK80n8arVKP7Et$aBKWm+vHZa/k0Vc9c+VE39TedSSkjQbdA3E0smqVz0I=',to_timestamp('14/04/24 03:51:08,260326000','DD/MM/RR HH24:MI:SSXFF'),'0','django',null,null,null,'0','1',to_timestamp('14/04/24 03:51:07,547328000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.AUTH_USER (ID,PASSWORD,LAST_LOGIN,IS_SUPERUSER,USERNAME,FIRST_NAME,LAST_NAME,EMAIL,IS_STAFF,IS_ACTIVE,DATE_JOINED) values ('7','pbkdf2_sha256$600000$X2F277u37fLt08ZHjZYhH4$Zc5/nLTaTCfAkmLh436WZtD2o1NKr7wEJxmNEEtXjHQ=',to_timestamp('14/04/24 05:14:36,900124000','DD/MM/RR HH24:MI:SSXFF'),'0','krink',null,null,null,'0','1',to_timestamp('14/04/24 05:14:36,136322000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.AUTH_USER (ID,PASSWORD,LAST_LOGIN,IS_SUPERUSER,USERNAME,FIRST_NAME,LAST_NAME,EMAIL,IS_STAFF,IS_ACTIVE,DATE_JOINED) values ('41','pbkdf2_sha256$600000$DcoOSmXtb42vkf0MHh4v4r$FWH70yEV06EKrjOEcASBCIzL6srd5ZxksmKO6tQ+Oso=',to_timestamp('22/04/24 13:22:44,859389000','DD/MM/RR HH24:MI:SSXFF'),'0','haze',null,null,null,'0','1',to_timestamp('22/04/24 13:22:43,985390000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.AUTH_USER (ID,PASSWORD,LAST_LOGIN,IS_SUPERUSER,USERNAME,FIRST_NAME,LAST_NAME,EMAIL,IS_STAFF,IS_ACTIVE,DATE_JOINED) values ('42','pbkdf2_sha256$600000$68HGPF3CGuLKksXeC4Ideu$cOqUa2uTj4YD69AKxgilyxxM/3kj+2fHz1jP4tfjfTk=',to_timestamp('29/04/24 10:49:40,963433000','DD/MM/RR HH24:MI:SSXFF'),'0','hash',null,null,null,'0','1',to_timestamp('22/04/24 13:24:07,426250000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.AUTH_USER (ID,PASSWORD,LAST_LOGIN,IS_SUPERUSER,USERNAME,FIRST_NAME,LAST_NAME,EMAIL,IS_STAFF,IS_ACTIVE,DATE_JOINED) values ('1','pbkdf2_sha256$600000$ISuBORFe8dXqrrNd6ZcI7y$wYXfvKV5SZrqdT26LsjxKtWG1ZHQ7Q3eEm3gJmHJgVA=',null,'1','jango',null,null,'n.sierra@duocuc.cl','1','1',to_timestamp('13/04/24 10:49:11,720058000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.AUTH_USER (ID,PASSWORD,LAST_LOGIN,IS_SUPERUSER,USERNAME,FIRST_NAME,LAST_NAME,EMAIL,IS_STAFF,IS_ACTIVE,DATE_JOINED) values ('2','pbkdf2_sha256$600000$xEDBpsNXM3QzZdfZYZQFvl$Up82mDJezuIAI20SDcVdPr8gnfv1uqE3Q+yBr/amOno=',null,'1','dujango',null,null,'n.sierra@duocuc.cl','1','1',to_timestamp('13/04/24 10:49:36,482126000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.AUTH_USER (ID,PASSWORD,LAST_LOGIN,IS_SUPERUSER,USERNAME,FIRST_NAME,LAST_NAME,EMAIL,IS_STAFF,IS_ACTIVE,DATE_JOINED) values ('3','pbkdf2_sha256$600000$7nRK88FoQ1Lf1R1NWLhekc$RuSPQiL4IKy28K8pAsZMTOMcGTmi8c0BTKvf56yFmH4=',to_timestamp('05/05/24 00:42:12,508862000','DD/MM/RR HH24:MI:SSXFF'),'1','kujango',null,null,'n.sierra@duocuc.cl','1','1',to_timestamp('13/04/24 10:50:54,856057000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.AUTH_USER (ID,PASSWORD,LAST_LOGIN,IS_SUPERUSER,USERNAME,FIRST_NAME,LAST_NAME,EMAIL,IS_STAFF,IS_ACTIVE,DATE_JOINED) values ('22','pbkdf2_sha256$600000$vuievpn9tulNScj0m5PsRY$mUv2j/2hnkrjm9iwWPMmVQmUQyRJnKvxUy3D+EEPy1M=',to_timestamp('15/04/24 23:10:07,426338000','DD/MM/RR HH24:MI:SSXFF'),'0','krauser',null,null,null,'0','1',to_timestamp('15/04/24 23:10:06,519345000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.AUTH_USER (ID,PASSWORD,LAST_LOGIN,IS_SUPERUSER,USERNAME,FIRST_NAME,LAST_NAME,EMAIL,IS_STAFF,IS_ACTIVE,DATE_JOINED) values ('23','pbkdf2_sha256$600000$NZISJbcKWRznMUSX4gU7hW$+ZZ91LawSg7nLgPUr6JUbuZTQh2TKGcpANEGOXuN8rw=',to_timestamp('15/04/24 23:14:30,495247000','DD/MM/RR HH24:MI:SSXFF'),'0','datoss',null,null,null,'0','1',to_timestamp('15/04/24 23:14:29,565247000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.AUTH_USER (ID,PASSWORD,LAST_LOGIN,IS_SUPERUSER,USERNAME,FIRST_NAME,LAST_NAME,EMAIL,IS_STAFF,IS_ACTIVE,DATE_JOINED) values ('61','pbkdf2_sha256$600000$z15KKa78eDKfmj5e09oK1N$81nUnba59GIWBMcd55WzH1PkSw4gpJjnIPHtBRTVABg=',to_timestamp('04/05/24 08:55:13,847556000','DD/MM/RR HH24:MI:SSXFF'),'0','Eluney',null,null,null,'0','1',to_timestamp('04/05/24 08:55:10,673155000','DD/MM/RR HH24:MI:SSXFF'));
REM INSERTING into C##PRUEBA.AUTH_USER_GROUPS
SET DEFINE OFF;
REM INSERTING into C##PRUEBA.AUTH_USER_USER_PERMISSIONS
SET DEFINE OFF;
REM INSERTING into C##PRUEBA.DJANGO_ADMIN_LOG
SET DEFINE OFF;
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('1',to_timestamp('13/04/24 11:01:55,861110000','DD/MM/RR HH24:MI:SSXFF'),'Desarrollado por Rockstar Games, Red Dead Redemption 2 es la secuela al juego de western de mundo abierto con el mismo nombre lanzado en 2010. Compra Red Dead Redemption 2 PC key y disfruta de una nue','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('2',to_timestamp('13/04/24 21:42:00,112316000','DD/MM/RR HH24:MI:SSXFF'),'Desarrollado por Rockstar Games, Red Dead Redemption 2 es la secuela al juego de western de mundo abierto con el mismo nombre lanzado en 2010. Compra Red Dead Redemption 2 PC key y disfruta de una nue','3','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('16',to_timestamp('13/04/24 22:09:51,883835000','DD/MM/RR HH24:MI:SSXFF'),'Devil May Cry 3 : Descubre el inquietante pasado de Dante en Devil May Cry 3, un juego que vuelve a sus raíces y te ve jugar como Dante, enfrentándote a peleas con monstruos que nunca antes habías vis','2','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('17',to_timestamp('13/04/24 22:10:04,537317000','DD/MM/RR HH24:MI:SSXFF'),'Monster Hunter World : Es un juego de acción desarrollado por Capcom. En Monster Hunter World recorrás el Nuevo Mundo y explorarás su ecosistema y siempre serás consciente de las criaturas monstruosas','2','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('18',to_timestamp('13/04/24 22:11:55,362315000','DD/MM/RR HH24:MI:SSXFF'),'¡Minecraft: Windows 10 edition :  permite unirte a la diversión en dispositivos que cuenten con el sistema operativo Windows 10!                                       Cuando hablamos de Minecraft, es ','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('19',to_timestamp('13/04/24 22:13:29,998181000','DD/MM/RR HH24:MI:SSXFF'),'Assassin''s Creed: Odyssey es la undécima entrega importante de la serie Assassin Creed. Es un juego de rol de acción desarrollado por Ubisoft. En esta ocasión viaja a la Antigua Grecia, año 431 a.C., ','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('20',to_timestamp('13/04/24 22:14:36,659328000','DD/MM/RR HH24:MI:SSXFF'),'Toylogic Inc. y Square Enix se unen para ofrecer una precuela mejorada del incomparable NieR: Automata donde un futuro distópico se personifica de la forma más bella posible. Se trata de una versión m','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('21',to_timestamp('13/04/24 22:16:19,776189000','DD/MM/RR HH24:MI:SSXFF'),'NieR Replicant ver.1.22474487139 :Toylogic Inc. y Square Enix se unen para ofrecer una precuela mejorada del incomparable NieR: Automata donde un futuro distópico se personifica de la forma más bella ','2','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('22',to_timestamp('13/04/24 22:18:26,686316000','DD/MM/RR HH24:MI:SSXFF'),'Adventure Time: The Secret of the Nameless Kingdom: La trama del juego toma Finn y Jake para descubrir los secretos a través de territorios inexplorados dentro de la Tierra de Ooo. El juego incluye un','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('23',to_timestamp('13/04/24 22:20:58,408011000','DD/MM/RR HH24:MI:SSXFF'),'Baldur''s Gate 3: ofrece una libertad sin precedentes para navegar, manipular y participar en un mundo vibrante repleto de personajes, peligros y engaños. Una narrativa épica y cinematográfica te acerc','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('24',to_timestamp('13/04/24 22:24:39,440317000','DD/MM/RR HH24:MI:SSXFF'),'Baldur''s Gate 3: ofrece una libertad sin precedentes para navegar, manipular y participar en un mundo vibrante repleto de personajes, peligros y engaños. Una narrativa épica y cinematográfica te acerc','2','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('25',to_timestamp('13/04/24 22:26:36,584599000','DD/MM/RR HH24:MI:SSXFF'),'Baldur''s Gate 3: ofrece una libertad sin precedentes para navegar, manipular y participar en un mundo vibrante repleto de personajes, peligros y engaños. Una narrativa épica y cinematográfica te acerc','2','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('26',to_timestamp('13/04/24 22:26:43,739901000','DD/MM/RR HH24:MI:SSXFF'),'Baldur''s Gate 3: ofrece una libertad sin precedentes para navegar, manipular y participar en un mundo vibrante repleto de personajes, peligros y engaños. Una narrativa épica y cinematográfica te acerc','2','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('27',to_timestamp('13/04/24 22:27:02,636312000','DD/MM/RR HH24:MI:SSXFF'),'Baldur''s Gate 3: ofrece una libertad sin precedentes para navegar, manipular y participar en un mundo vibrante repleto de personajes, peligros y engaños. Una narrativa épica y cinematográfica te acerc','2','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('28',to_timestamp('13/04/24 22:27:11,940082000','DD/MM/RR HH24:MI:SSXFF'),'Baldur''s Gate 3: ofrece una libertad sin precedentes para navegar, manipular y participar en un mundo vibrante repleto de personajes, peligros y engaños. Una narrativa épica y cinematográfica te acerc','2','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('29',to_timestamp('13/04/24 22:29:09,268189000','DD/MM/RR HH24:MI:SSXFF'),'Baldur''s Gate 3: ofrece una libertad sin precedentes para navegar, manipular y participar en un mundo vibrante repleto de personajes, peligros y engaños. Una narrativa épica y cinematográfica te acerc','2','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('30',to_timestamp('13/04/24 22:29:21,590110000','DD/MM/RR HH24:MI:SSXFF'),'Baldur''s Gate 3: ofrece una libertad sin precedentes para navegar, manipular y participar en un mundo vibrante repleto de personajes, peligros y engaños. Una narrativa épica y cinematográfica te acerc','2','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('31',to_timestamp('13/04/24 22:31:05,931685000','DD/MM/RR HH24:MI:SSXFF'),'Baldur''s Gate 3: ofrece una libertad sin precedentes para navegar, manipular y participar en un mundo vibrante repleto de personajes, peligros y engaños. Una narrativa épica y cinematográfica te acerc','2','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('32',to_timestamp('13/04/24 22:32:55,338412000','DD/MM/RR HH24:MI:SSXFF'),'Baldur''s Gate 3: ofrece una libertad sin precedentes para navegar, manipular y participar en un mundo vibrante repleto de personajes, peligros y engaños. Una narrativa épica y cinematográfica te acerc','2','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('33',to_timestamp('13/04/24 22:34:36,237744000','DD/MM/RR HH24:MI:SSXFF'),'Baldur''s Gate 3: ofrece una libertad sin precedentes para navegar, manipular y participar en un mundo vibrante repleto de personajes, peligros y engaños. Una narrativa épica y cinematográfica te acerc','3','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('34',to_timestamp('14/04/24 02:27:02,327162000','DD/MM/RR HH24:MI:SSXFF'),'Lords of the Fallen : Embárcate en esta gran aventura en Lords of the Fallen, donde te esperan la convergencia de dos mundos, el dominio del combate, la conquista de enemigos colosales, el manejo de u','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('35',to_timestamp('14/04/24 02:28:17,833323000','DD/MM/RR HH24:MI:SSXFF'),'Nunca has recibido tu carta de Hogwarts. Gran cosa, ahora puedes visitar y estudiar en la famosa Escuela de Magia y Hechicería en el juego RPG de acción de mundo abierto desarrollado por Avalanche Sof','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('36',to_timestamp('14/04/24 02:30:35,121999000','DD/MM/RR HH24:MI:SSXFF'),'¿Cómo lo llevarías en un mundo golpeado por un apocalipsis nuclear? Hay otros supervivientes, pero el mundo es diferente al idílico lugar del que vienes. Tendrás que adaptarte, luchar y mejorar tu con','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('37',to_timestamp('14/04/24 02:31:44,057447000','DD/MM/RR HH24:MI:SSXFF'),'>Code Vein key trae un RPG con acción de calidad directamente a tu puerta. Desarrollado y publicado por BANDAI NAMCO, el título trae dificultad, una historia intrincada, y muchas de las ya conocidas c','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('38',to_timestamp('14/04/24 02:33:43,259067000','DD/MM/RR HH24:MI:SSXFF'),'Darksiders Warmastered Edition se centra en Guerra, uno de los Cuatro Jinetes, que tras ser engañado rompe el Pacto entre Cielo e Infierno. Acude a la Tierra y desata el Apocalipsis. A partir de ahí G','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('39',to_timestamp('14/04/24 02:35:04,372601000','DD/MM/RR HH24:MI:SSXFF'),'Desarrollado por Rockstar Games, Red Dead Redemption 2 es la secuela al juego de western de mundo abierto con el mismo nombre lanzado en 2010. Compra Red Dead Redemption 2 PC key y disfruta de una nue','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('40',to_timestamp('14/04/24 02:37:49,642317000','DD/MM/RR HH24:MI:SSXFF'),'Call of Duty: Ghosts es la sexta incorporación importante a la serie de juegos de disparos de acción COD desarrollada por Infinity Ward. Estados Unidos ya no es una potencia mundial, la guerra ha desp','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('41',to_timestamp('14/04/24 02:41:09,203319000','DD/MM/RR HH24:MI:SSXFF'),'Battlefield 4 : ¡La clave de Battlefield 4 (Edición Premium) contiene la mejor experiencia en el campo de batalla! Al comprar la clave del paquete Battlefield 4 Premium, obtendrás el juego BF4 origina','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('42',to_timestamp('14/04/24 02:42:18,061944000','DD/MM/RR HH24:MI:SSXFF'),'Borderlands (GOTY) : La clave de Borderlands (GOTY), o Edición Juego del Año, ofrece la mejor y más completa experiencia que el juego FPS de disparos y saqueo de Gearbox Software puede ofrecer. Border','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('43',to_timestamp('14/04/24 02:43:46,672328000','DD/MM/RR HH24:MI:SSXFF'),'Warhammer: Verminitide 2 key, desarrollado por Fatshark, es una mezcla seria de elementos de hack and slash, cooperativo en primera persona y RPG. El juego está ambientado en el universo ficticio de W','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('44',to_timestamp('14/04/24 02:45:14,736315000','DD/MM/RR HH24:MI:SSXFF'),'Bioshock es un pionero en el género de disparos de ciencia ficción que no solo presenta armas mortales y explosivas, sino que también te permite convertirte en un arma mediante la modificación del ADN','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('45',to_timestamp('14/04/24 02:47:13,901328000','DD/MM/RR HH24:MI:SSXFF'),'¡Compra Doom: Eternal Key para experimentar un juego FPS que está a años luz de su predecesor! La escala, lo que está en juego, la estructura misma del juego y el sistema de combate: ¡todo está en un ','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('46',to_timestamp('14/04/24 02:49:17,014331000','DD/MM/RR HH24:MI:SSXFF'),'Days Gone: ¿Sobrevivirás a los horrores de un mundo moribundo o tu búsqueda de una razón para vivir será en vano? Pon a prueba tu determinación en la nueva entrega de SIE Bend Studio y Sony Interactiv','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('47',to_timestamp('14/04/24 02:50:18,144884000','DD/MM/RR HH24:MI:SSXFF'),'Amnesia: The Bunker en Steam es el sello distintivo de los títulos de horror, ¡listo para llevar a los jugadores a una experiencia de juego única! Hecho para jugadores como tú por el famoso Frictional','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('48',to_timestamp('14/04/24 02:52:30,301187000','DD/MM/RR HH24:MI:SSXFF'),'The Outlast Trials : Durante la Guerra Fría, The Outlast Trials te sumerge en una escalofriante historia en la que individuos desprevenidos son obligados por Murkoff Corporation a convertirse en sujet','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('49',to_timestamp('14/04/24 02:53:50,247076000','DD/MM/RR HH24:MI:SSXFF'),'The Evil Within 2 : ¿Qué harías por tu hija? Para el Detective Sebastián Castellanos, la respuesta es simple: cualquier cosa. Para salvar a su hija, este policía tendrá que sumergirse en mundo de STEM','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('50',to_timestamp('14/04/24 02:55:03,946974000','DD/MM/RR HH24:MI:SSXFF'),'Little Nightmares 2 : la secuela Little Nightmares II ofrece una extraordinaria experiencia de juego indie en la que la acción y los elementos de horror suave se entrelazan a la perfección. Debido a l','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('51',to_timestamp('14/04/24 02:56:40,624199000','DD/MM/RR HH24:MI:SSXFF'),'Dying Light 2 Stay Human : entra un mundo roto y dividido por un virus que convierte todo lo vivo en un monstruo corrupto nocturno ansioso de sangre. Este mundo inolvidable infectado ha transformado l','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('61',to_timestamp('29/04/24 08:56:04,826586000','DD/MM/RR HH24:MI:SSXFF'),'Adventure Time: The Secret of the Nameless Kingdom: La trama del juego toma Finn y Jake para descubrir los secretos a través de territorios inexplorados dentro de la Tierra de Ooo. El juego incluye un','3','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('62',to_timestamp('29/04/24 08:56:09,619828000','DD/MM/RR HH24:MI:SSXFF'),'Adventure Time: The Secret of the Nameless Kingdom: La trama del juego toma Finn y Jake para descubrir los secretos a través de territorios inexplorados dentro de la Tierra de Ooo. El juego incluye un','3','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('63',to_timestamp('29/04/24 09:14:33,656191000','DD/MM/RR HH24:MI:SSXFF'),'Adventure Time: The Secret of the Nameless Kingdom: La trama del juego toma Finn y Jake para descubrir los secretos a través de territorios inexplorados dentro de la Tierra de Ooo. El juego incluye un','3','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('64',to_timestamp('29/04/24 09:21:23,797320000','DD/MM/RR HH24:MI:SSXFF'),'Assassin''s Creed: Odyssey es la undécima entrega importante de la serie Assassin Creed. Es un juego de rol de acción desarrollado por Ubisoft. En esta ocasión viaja a la Antigua Grecia, año 431 a.C., ','3','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('65',to_timestamp('29/04/24 09:55:45,635377000','DD/MM/RR HH24:MI:SSXFF'),'Adventure Time: The Secret of the Nameless Kingdom: La trama del juego toma Finn y Jake para descubrir los secretos a través de territorios inexplorados dentro de la Tierra de Ooo. El juego incluye un','3','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('66',to_timestamp('29/04/24 09:55:49,203444000','DD/MM/RR HH24:MI:SSXFF'),'Adventure Time: The Secret of the Nameless Kingdom: La trama del juego toma Finn y Jake para descubrir los secretos a través de territorios inexplorados dentro de la Tierra de Ooo. El juego incluye un','3','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('67',to_timestamp('29/04/24 10:27:15,000506000','DD/MM/RR HH24:MI:SSXFF'),'Adventure Time: The Secret of the Nameless Kingdom: La trama del juego toma Finn y Jake para descubrir los secretos a través de territorios inexplorados dentro de la Tierra de Ooo. El juego incluye un','3','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('3',to_timestamp('13/04/24 21:42:27,513980000','DD/MM/RR HH24:MI:SSXFF'),'Desarrollado por Rockstar Games, Red Dead Redemption 2 es la secuela al juego de western de mundo abierto con el mismo nombre lanzado en 2010. Compra Red Dead Redemption 2 PC key y disfruta de una nue','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('4',to_timestamp('13/04/24 21:43:21,530956000','DD/MM/RR HH24:MI:SSXFF'),'Compra la clave Steam de PAYDAY 2 y obtén acceso a un juego FPS cooperativo desarrollado por Overkill Software. Ya conoces esos atracos geniales que ves en las películas; ¿Dónde un grupo de chicos hac','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('5',to_timestamp('13/04/24 22:00:07,218117000','DD/MM/RR HH24:MI:SSXFF'),'La libertad, la paz y la democracia son los derechos fundamentales de la civilización nacida en la Supertierra, parte integral de su propia existencia. Sin embargo, a medida que la guerra continúa hac','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('6',to_timestamp('13/04/24 22:01:41,194318000','DD/MM/RR HH24:MI:SSXFF'),'Compra la clave de Kingdom Come: Deliverance y entra en un mundo abierto basado en una historia ambientado en la época del Sacro Imperio Romano. El juego fue desarrollado por Warhorse Studios y es una','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('7',to_timestamp('13/04/24 22:02:55,575188000','DD/MM/RR HH24:MI:SSXFF'),'Dark Souls III key ofrece un RPG de acción oscuro y enrevesado de los desarrolladores FromSoftware. El fuego casi se ha extinguido, y allá donde el fuego muere viene la oscuridad que sumerge a la huma','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('8',to_timestamp('13/04/24 22:04:16,148898000','DD/MM/RR HH24:MI:SSXFF'),'Descubre el inquietante pasado de Dante en Devil May Cry 3, un juego que vuelve a sus raíces y te ve jugar como Dante, enfrentándote a peleas con monstruos que nunca antes habías visto, todo en el cam','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('9',to_timestamp('13/04/24 22:06:23,105376000','DD/MM/RR HH24:MI:SSXFF'),'Dragon''s Dogma: Dark Arisen Steam key es un juego de rol de acción hack-and-slash desarrollado por Capcom. Dark Arisen es el relanzamiento y la expansión del juego original. Contiene todo el contenido','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('10',to_timestamp('13/04/24 22:07:53,971495000','DD/MM/RR HH24:MI:SSXFF'),'Es un juego de acción desarrollado por Capcom. En Monster Hunter World recorrás el Nuevo Mundo y explorarás su ecosistema y siempre serás consciente de las criaturas monstruosas con las que convives. ','1','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('11',to_timestamp('13/04/24 22:08:30,932331000','DD/MM/RR HH24:MI:SSXFF'),'Red Dead Redemption 2: Desarrollado por Rockstar Games, Red Dead Redemption 2 es la secuela al juego de western de mundo abierto con el mismo nombre lanzado en 2010. Compra Red Dead Redemption 2 PC ke','2','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('12',to_timestamp('13/04/24 22:08:41,675321000','DD/MM/RR HH24:MI:SSXFF'),'Pay Day 2 : Compra la clave Steam de PAYDAY 2 y obtén acceso a un juego FPS cooperativo desarrollado por Overkill Software. Ya conoces esos atracos geniales que ves en las películas; ¿Dónde un grupo d','2','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('13',to_timestamp('13/04/24 22:09:07,186185000','DD/MM/RR HH24:MI:SSXFF'),'Helldivers 2: La libertad, la paz y la democracia son los derechos fundamentales de la civilización nacida en la Supertierra, parte integral de su propia existencia. Sin embargo, a medida que la guerr','2','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('14',to_timestamp('13/04/24 22:09:20,846785000','DD/MM/RR HH24:MI:SSXFF'),'Kingdom Come Deliverance : Compra la clave de Kingdom Come: Deliverance y entra en un mundo abierto basado en una historia ambientado en la época del Sacro Imperio Romano. El juego fue desarrollado po','2','8','3');
Insert into C##PRUEBA.DJANGO_ADMIN_LOG (ID,ACTION_TIME,OBJECT_REPR,ACTION_FLAG,CONTENT_TYPE_ID,USER_ID) values ('15',to_timestamp('13/04/24 22:09:41,450133000','DD/MM/RR HH24:MI:SSXFF'),'Dark Souls 3 : Dark Souls III key ofrece un RPG de acción oscuro y enrevesado de los desarrolladores FromSoftware. El fuego casi se ha extinguido, y allá donde el fuego muere viene la oscuridad que su','2','8','3');
REM INSERTING into C##PRUEBA.DJANGO_CONTENT_TYPE
SET DEFINE OFF;
Insert into C##PRUEBA.DJANGO_CONTENT_TYPE (ID,APP_LABEL,MODEL) values ('1','admin','logentry');
Insert into C##PRUEBA.DJANGO_CONTENT_TYPE (ID,APP_LABEL,MODEL) values ('2','auth','permission');
Insert into C##PRUEBA.DJANGO_CONTENT_TYPE (ID,APP_LABEL,MODEL) values ('3','auth','group');
Insert into C##PRUEBA.DJANGO_CONTENT_TYPE (ID,APP_LABEL,MODEL) values ('4','auth','user');
Insert into C##PRUEBA.DJANGO_CONTENT_TYPE (ID,APP_LABEL,MODEL) values ('5','contenttypes','contenttype');
Insert into C##PRUEBA.DJANGO_CONTENT_TYPE (ID,APP_LABEL,MODEL) values ('6','sessions','session');
Insert into C##PRUEBA.DJANGO_CONTENT_TYPE (ID,APP_LABEL,MODEL) values ('7','miApp','micuentatf');
Insert into C##PRUEBA.DJANGO_CONTENT_TYPE (ID,APP_LABEL,MODEL) values ('8','miApp','producto');
Insert into C##PRUEBA.DJANGO_CONTENT_TYPE (ID,APP_LABEL,MODEL) values ('21','authtoken','token');
Insert into C##PRUEBA.DJANGO_CONTENT_TYPE (ID,APP_LABEL,MODEL) values ('22','authtoken','tokenproxy');
REM INSERTING into C##PRUEBA.DJANGO_MIGRATIONS
SET DEFINE OFF;
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('1','contenttypes','0001_initial',to_timestamp('13/04/24 10:45:11,889814000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('2','auth','0001_initial',to_timestamp('13/04/24 10:45:12,752810000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('3','admin','0001_initial',to_timestamp('13/04/24 10:45:12,956815000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('4','admin','0002_logentry_remove_auto_add',to_timestamp('13/04/24 10:45:12,995812000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('5','admin','0003_logentry_add_action_flag_choices',to_timestamp('13/04/24 10:45:13,038880000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('6','contenttypes','0002_remove_content_type_name',to_timestamp('13/04/24 10:45:14,752809000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('7','auth','0002_alter_permission_name_max_length',to_timestamp('13/04/24 10:45:14,840810000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('8','auth','0003_alter_user_email_max_length',to_timestamp('13/04/24 10:45:14,893874000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('9','auth','0004_alter_user_username_opts',to_timestamp('13/04/24 10:45:14,933809000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('10','auth','0005_alter_user_last_login_null',to_timestamp('13/04/24 10:45:14,997811000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('11','auth','0006_require_contenttypes_0002',to_timestamp('13/04/24 10:45:15,044811000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('12','auth','0007_alter_validators_add_error_messages',to_timestamp('13/04/24 10:45:15,088808000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('13','auth','0008_alter_user_username_max_length',to_timestamp('13/04/24 10:45:15,152809000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('14','auth','0009_alter_user_last_name_max_length',to_timestamp('13/04/24 10:45:15,202874000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('15','auth','0010_alter_group_name_max_length',to_timestamp('13/04/24 10:45:15,255814000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('16','auth','0011_update_proxy_permissions',to_timestamp('13/04/24 10:45:15,294811000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('17','auth','0012_alter_user_first_name_max_length',to_timestamp('13/04/24 10:45:15,345810000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('18','miApp','0001_initial',to_timestamp('13/04/24 10:45:15,453809000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('19','miApp','0002_producto',to_timestamp('13/04/24 10:45:15,540812000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('20','sessions','0001_initial',to_timestamp('13/04/24 10:45:15,595816000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('21','authtoken','0001_initial',to_timestamp('22/04/24 12:45:24,743742000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('22','authtoken','0002_auto_20160226_1747',to_timestamp('22/04/24 12:45:24,995732000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('23','authtoken','0003_tokenproxy',to_timestamp('22/04/24 12:45:25,032736000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##PRUEBA.DJANGO_MIGRATIONS (ID,APP,NAME,APPLIED) values ('24','authtoken','0004_alter_tokenproxy_options',to_timestamp('22/04/24 12:45:25,072736000','DD/MM/RR HH24:MI:SSXFF'));
REM INSERTING into C##PRUEBA.DJANGO_SESSION
SET DEFINE OFF;
Insert into C##PRUEBA.DJANGO_SESSION (SESSION_KEY,EXPIRE_DATE) values ('9pize28zsfiowsyi4g6spzv77khdqo97',to_timestamp('27/04/24 21:58:43,552328000','DD/MM/RR HH24:MI:SSXFF'));
REM INSERTING into C##PRUEBA.MIAPP_MICUENTATF
SET DEFINE OFF;
Insert into C##PRUEBA.MIAPP_MICUENTATF (ID,TITLE,CREATED,DATECOMPLETED,IMPORTANT,USER_ID) values ('1','Cuenta',to_timestamp('26/04/24 03:50:37,872552000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('25/04/24 23:50:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','5');
Insert into C##PRUEBA.MIAPP_MICUENTATF (ID,TITLE,CREATED,DATECOMPLETED,IMPORTANT,USER_ID) values ('23','jango',to_timestamp('29/04/24 21:22:25,585808000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('29/04/24 17:22:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','3');
Insert into C##PRUEBA.MIAPP_MICUENTATF (ID,TITLE,CREATED,DATECOMPLETED,IMPORTANT,USER_ID) values ('24','jango',to_timestamp('29/04/24 21:33:58,738520000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('29/04/24 17:22:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','3');
Insert into C##PRUEBA.MIAPP_MICUENTATF (ID,TITLE,CREATED,DATECOMPLETED,IMPORTANT,USER_ID) values ('26','jango',to_timestamp('29/04/24 21:51:45,673807000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('29/04/24 17:22:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','3');
Insert into C##PRUEBA.MIAPP_MICUENTATF (ID,TITLE,CREATED,DATECOMPLETED,IMPORTANT,USER_ID) values ('27','jango',to_timestamp('29/04/24 21:51:46,625809000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('29/04/24 17:22:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','3');
Insert into C##PRUEBA.MIAPP_MICUENTATF (ID,TITLE,CREATED,DATECOMPLETED,IMPORTANT,USER_ID) values ('28','jango',to_timestamp('29/04/24 21:51:47,411808000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('29/04/24 17:22:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','3');
Insert into C##PRUEBA.MIAPP_MICUENTATF (ID,TITLE,CREATED,DATECOMPLETED,IMPORTANT,USER_ID) values ('29','jango',to_timestamp('29/04/24 21:56:34,908807000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('29/04/24 17:22:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','3');
Insert into C##PRUEBA.MIAPP_MICUENTATF (ID,TITLE,CREATED,DATECOMPLETED,IMPORTANT,USER_ID) values ('25','jango',to_timestamp('29/04/24 21:37:43,681941000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('29/04/24 17:22:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','3');
Insert into C##PRUEBA.MIAPP_MICUENTATF (ID,TITLE,CREATED,DATECOMPLETED,IMPORTANT,USER_ID) values ('21','Lunes AM',to_timestamp('29/04/24 06:53:14,793335000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('29/04/24 02:52:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','3');
Insert into C##PRUEBA.MIAPP_MICUENTATF (ID,TITLE,CREATED,DATECOMPLETED,IMPORTANT,USER_ID) values ('22','Lunes',to_timestamp('29/04/24 11:58:22,259353000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('29/04/24 07:58:00,000000000','DD/MM/RR HH24:MI:SSXFF'),'1','3');
REM INSERTING into C##PRUEBA.MIAPP_PRODUCTO
SET DEFINE OFF;
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0012','Adventure Time: The Secret of the Nameless Kingdom: La trama del juego toma Finn y Jake para descubrir los secretos a través de territorios inexplorados dentro de la Tierra de Ooo. El juego incluye un juego de aventura de perspectiva de arriba hacia abajo con elementos de rompecabezas, de forma similar a Explore the Dungeon Because I Don''t Know!','83000','30','0','https://cdn-products.eneba.com/resized-products/P4pEe1ryrpV-LjVZBDOWt8MZDf9QJ7G77uBpYXIZ7ys_350x200_1x-0.jpeg','2');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0011','NieR Replicant ver.1.22474487139 :Toylogic Inc. y Square Enix se unen para ofrecer una precuela mejorada del incomparable NieR: Automata donde un futuro distópico se personifica de la forma más bella posible. Se trata de una versión mejorada de NieR Replicant lanzada exclusivamente en Japón. Ahora, por fin puedes disfrutar de la aclamada precuela del RPG para un jugador y embarcarte en el viaje de un joven protagonista que lucha por encontrar una cura para su hermana, que sufre una enfermedad conocida como necrosis rúnica.','23000','25','0','https://cdn-products.eneba.com/resized-products/atilyfmTdeCtjqWAUEA7ZTpjnLQ5oAOGAfKQEkjSbx4_350x200_1x-0.jpeg','2');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0013','Baldur''s Gate 3: ofrece una libertad sin precedentes para navegar, manipular y participar en un mundo vibrante repleto de personajes, peligros y engaños. Una narrativa épica y cinematográfica te acerca más que nunca a tus personajes. Viaja por bosques llenos de sombras, adéntrate en las mágicas cavernas de la Infraoscuridad y atraviesa el vasto paisaje urbano de Baldur''s Gate. Tus decisiones forjarán tu legado. ¡Da forma a tu aventura con Baldur''s Gate 3!','72000','12','0','https://cdn-products.eneba.com/resized-products/KawDyHCR648cl4vrgkKEXbP1idCGK7ETqxux3HCNhak_350x200_1x-0.png','3');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0019','Call of Duty: Ghosts es la sexta incorporación importante a la serie de juegos de disparos de acción COD desarrollada por Infinity Ward. Estados Unidos ya no es una potencia mundial, la guerra ha desplazado el eje del poder y el enemigo desconocido se acerca. Las ramas militares se fusionaron para formar una unidad especial, llamada Fantasmas. Tu objetivo es exterminar la amenaza que se avecina, utilizando todos los medios necesarios.','54000','15','0','https://cdn-products.eneba.com/resized-products/KRXZljO_350x200_1x-0.jpg','4');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0055','Adventure Time: The Secret of the Nameless Kingdom: La trama del juego toma Finn y Jake para descubrir los secretos a través de territorios inexplorados dentro de la Tierra de Ooo. El juego incluye un juego de aventura de perspectiva de arriba hacia abajo con elementos de rompecabezas, de forma similar a Explore the Dungeon Because I Don''t Know!','83000','30','0','https://cdn-products.eneba.com/resized-products/P4pEe1ryrpV-LjVZBDOWt8MZDf9QJ7G77uBpYXIZ7ys_350x200_1x-0.jpeg','2');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0014','Lords of the Fallen : Embárcate en esta gran aventura en Lords of the Fallen, donde te esperan la convergencia de dos mundos, el dominio del combate, la conquista de enemigos colosales, el manejo de una magia sobrecogedora, los lazos forjados en el modo multijugador, los encuentros enigmáticos y el viaje personalizado.','35000','15','0','https://cdn-products.eneba.com/resized-products/iew-9FiCLGwZ6DiZZBVr9J1fUbReHHcwtmDNhOn4dxY_350x200_1x-0.jpg','3');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0015','Nunca has recibido tu carta de Hogwarts. Gran cosa, ahora puedes visitar y estudiar en la famosa Escuela de Magia y Hechicería en el juego RPG de acción de mundo abierto desarrollado por Avalanche Software - Hogwarts Legacy. Como estudiante, experimentarás la vida en Hogwarts, desde asistir a clase y lanzar hechizos hasta explorar el castillo y sus terrenos llenos de magia y misterio. Coge tu varita, lanza Accio on Hogwarts Legacy Código de Steam, ¡y súbete al Expreso de Hogwarts!.','22000','14','0','https://cdn-products.eneba.com/resized-products/pWjtGdm5_gHCDbrLlHo_OtPbUsin7dyCzylQ0snaSoM_350x200_1x-0.jpg','3');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0016','¿Cómo lo llevarías en un mundo golpeado por un apocalipsis nuclear? Hay otros supervivientes, pero el mundo es diferente al idílico lugar del que vienes. Tendrás que adaptarte, luchar y mejorar tu condición para asegurar tu supervivencia, más que probar suerte. Fallout 4 es RPG post-apocalíptico de mundo abierto desarrollado por Bethesda Game Studios y es algo que simplemente no puedes dejar escapar.','5500','15','0','https://cdn-products.eneba.com/resized-products/vfyzvftuigeslbhueeht_350x200_1x-0.jpg','3');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0017','>Code Vein key trae un RPG con acción de calidad directamente a tu puerta. Desarrollado y publicado por BANDAI NAMCO, el título trae dificultad, una historia intrincada, y muchas de las ya conocidas características comunes a los juegos JRPG. Crea y personaliza tu personaje hasta el detalle más minucioso y adéntrate en este futuro distópico donde para sobrevivir, tendrás que demostrar tu valía. Consume o sé consumido: esa es la norma en este nuevo mundo.','11500','20','0','https://cdn-products.eneba.com/resized-products/V6kicjL0mU7qiIzVQ7661G-lI241Gmhkd2cwg4RjqoE_350x200_1x-0.jpeg','3');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0018','Darksiders Warmastered Edition se centra en Guerra, uno de los Cuatro Jinetes, que tras ser engañado rompe el Pacto entre Cielo e Infierno. Acude a la Tierra y desata el Apocalipsis. A partir de ahí Guerra entrará en una espiral de venganza y redención en la que tendrá que averiguar qué es lo que realmente ha pasado y en la que tendrá que recuperar tanto sus poderes como su honor.','12900','22','0','https://cdn-products.eneba.com/resized-products/bGKMfat_350x200_1x-0.jpg','3');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0001','Desarrollado por Rockstar Games, Red Dead Redemption 2 es la secuela al juego de western de mundo abierto con el mismo nombre lanzado en 2010. Compra Red Dead Redemption 2 PC key y disfruta de una nueva experiencia gaming de Rockstar, tan épica como las que nos tienen acostumbrados. Como Red Dead Redemption 2 viene de las consolas al PC, habrá un par de cambios y añadidos que mejoran la ya excelente nueva entrega de esta franquicia del Salvaje Oeste.','26500','19','0','https://cdn-products.eneba.com/resized-products/6M1qP76B-j6vdX0T4bFCHgJeX99MaKBpXFxbpif1MqY_350x200_1x-0.jpeg','1');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0020','Battlefield 4 : ¡La clave de Battlefield 4 (Edición Premium) contiene la mejor experiencia en el campo de batalla! Al comprar la clave del paquete Battlefield 4 Premium, obtendrás el juego BF4 original más una membresía BF4 Premium que incluye todos los paquetes de expansión de 5digital. ¡Toneladas de contenido nuevo con 20 mapas adicionales, un montón de modos de juego nuevos, varias armas nuevas, vehículos, logros, trofeos y más!','14000','20','0','https://cdn-products.eneba.com/resized-products/ljvyF49kIobCbOAq_5sgiW4DFSc7xSMEb9O353io1JQ_350x200_1x-0.jpeg','4');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0021','Borderlands (GOTY) : La clave de Borderlands (GOTY), o Edición Juego del Año, ofrece la mejor y más completa experiencia que el juego FPS de disparos y saqueo de Gearbox Software puede ofrecer. Borderlands 3 ha sido confirmado oficialmente, pero aún queda bastante tiempo para la ocasión. Mientras esperas, ¿por qué no refrescar tu memoria con el juego del que ha surgido esta inédita saga?.','13600','25','0','https://cdn-products.eneba.com/resized-products/zGSwFndMOL3Bp8waBE-SAdrn4AIEee05eXnAPZaOV_o_350x200_1x-0.jpeg','4');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0022','Warhammer: Verminitide 2 key, desarrollado por Fatshark, es una mezcla seria de elementos de hack and slash, cooperativo en primera persona y RPG. El juego está ambientado en el universo ficticio de Warhammer, donde las fuerzas del mal han asolado la Tierra Media. El caos y el terror asolan las tierras y depende de ti y de tu equipo de héroes acabar con la recién formada alianza entre nórdicos potenciados, ratas humanoides y muchos de sus partidarios. Con el poder limpiador de hachas, espadas de dos manos, martillos y otras armas únicas, podrás mirar al mal directamente a los ojos.','2800','25','0','https://cdn-products.eneba.com/resized-products/pocat2ipqrkhiguuev1f_350x200_1x-0.jpg','4');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0023','Bioshock es un pionero en el género de disparos de ciencia ficción que no solo presenta armas mortales y explosivas, sino que también te permite convertirte en un arma mediante la modificación del ADN. ¡La cantidad de posibles giros y vueltas en cada juego asegura que nunca dos juegos se sientan iguales!                                      Este trabajo de 2K te lleva a un mundo en el que necesitas piratear todo tipo de sistemas para mejorar tu armamento.','11200','25','0','https://cdn-products.eneba.com/resized-products/jrpib8t74zhaapqq2idi_350x200_1x-0.jpg','4');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0024','¡Compra Doom: Eternal Key para experimentar un juego FPS que está a años luz de su predecesor! La escala, lo que está en juego, la estructura misma del juego y el sistema de combate: ¡todo está en un nivel completamente nuevo! ¡No pierdas la oportunidad de convertirte una vez más en Doom Slayer, un guerrero feroz temido por las fuerzas del infierno!.','15000','35','0','https://cdn-products.eneba.com/resized-products/STix0fN09DuS6nUGIzX2oMzN_IVrIOKKtDd-KactjMw_350x200_1x-0.jpeg','4');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0025','Days Gone: ¿Sobrevivirás a los horrores de un mundo moribundo o tu búsqueda de una razón para vivir será en vano? Pon a prueba tu determinación en la nueva entrega de SIE Bend Studio y Sony Interactive Entertainment que combina la acción y la aventura con elementos del género de supervivencia: ¡Days Gone!','17500','25','0','https://cdn-products.eneba.com/resized-products/bwF96S6ImbL-4l9gRyo8Nvd-oWcbGItWyfaMC_0A7sk_350x200_1x-0.jpeg','5');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0026','Amnesia: The Bunker en Steam es el sello distintivo de los títulos de horror, ¡listo para llevar a los jugadores a una experiencia de juego única! Hecho para jugadores como tú por el famoso Frictional Games, ¡el título supera las expectativas y proporciona un entretenimiento único para los fans de los juegos de horror! No es ningún secreto que la clave para disfrutar de los juegos es encontrar el juego adecuado que se adapte a tus preferencias y te enganche en el mundo virtual, así que no lo dudes más.','5500','22','0','https://cdn-products.eneba.com/resized-products/bMlKcCl-QwI7hlmUguacQkHoJDK1rXiWqUscpO9wWBk_350x200_1x-0.png','5');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0027','The Outlast Trials : Durante la Guerra Fría, The Outlast Trials te sumerge en una escalofriante historia en la que individuos desprevenidos son obligados por Murkoff Corporation a convertirse en sujetos de pruebas para técnicas experimentales de lavado de cerebro y control mental. Este desgarrador mundo está plagado de desconfianza, miedo y violencia, donde tu integridad moral, resistencia y estabilidad mental son llevadas al límite con el pretexto del progreso científico y el beneficio empresarial.','35000','25','0','https://cdn-products.eneba.com/resized-products/6P6lS2QRQDACXYWVL7g-emjYYz9nKtG5yOksLE9JTUs_350x200_1x-0.jpg','5');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0030','The Evil Within 2 : ¿Qué harías por tu hija? Para el Detective Sebastián Castellanos, la respuesta es simple: cualquier cosa. Para salvar a su hija, este policía tendrá que sumergirse en mundo de STEM, donde terribles¿Qué harías por tu hija? Para el Detective Sebastián Castellanos, la respuesta es simple: cualquier cosa. Para salvar a su hija, este policía tendrá que sumergirse en mundo de STEM, donde terribles amenazas le esperan en cada esquina.','5800','12','0','https://cdn-products.eneba.com/resized-products/z9ooqscxnvftgbpktcgt_350x200_1x-0.jpg','5');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0031','Little Nightmares 2 : la secuela Little Nightmares II ofrece una extraordinaria experiencia de juego indie en la que la acción y los elementos de horror suave se entrelazan a la perfección. Debido a la misteriosa Transmisión, Mono aparece en un mundo distorsionado de forma espeluznante, e intenta encontrar la fuente de esta enigmática Transmisión con la ayuda de una chica llamada Six. Compra Little Nightmares 2 código de Steam a un precio más barato y emprende aventuras en un mundo atmosférico donde todo lo que conoces está distorsionado y presentado en una luz espeluznante!.','19000','22','0','https://cdn-products.eneba.com/resized-products/6Xa9O0zV5oHxEzz5aGdBWY8ZDkC_cl09NuvKyInuRww_350x200_1x-0.jpeg','5');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0032','Dying Light 2 Stay Human : entra un mundo roto y dividido por un virus que convierte todo lo vivo en un monstruo corrupto nocturno ansioso de sangre. Este mundo inolvidable infectado ha transformado lo que queda de la humanidad en su peor cara. Las últimas ciudades supervivientes han caído en una especie de edad media, los bandidos caminan libres por las calles durante el día, y los zombies entran en la noche: nadie está nunca a salvo, y ahí es donde tú, Aiden Caldwell, entra en acción.','34000','24','0','https://cdn-products.eneba.com/resized-products/e-yyCgIlXPmlV_QGqiHeIr2mZa0NEiOj0J9UEw6yuQE_350x200_1x-0.jpg','5');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0056','Adventure Time: The Secret of the Nameless Kingdom: La trama del juego toma Finn y Jake para descubrir los secretos a través de territorios inexplorados dentro de la Tierra de Ooo. El juego incluye un juego de aventura de perspectiva de arriba hacia abajo con elementos de rompecabezas, de forma similar a Explore the Dungeon Because I Don''t Know!','83000','30','0','https://cdn-products.eneba.com/resized-products/P4pEe1ryrpV-LjVZBDOWt8MZDf9QJ7G77uBpYXIZ7ys_350x200_1x-0.jpeg','2');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0002','Pay Day 2 : Compra la clave Steam de PAYDAY 2 y obtén acceso a un juego FPS cooperativo desarrollado por Overkill Software. Ya conoces esos atracos geniales que ves en las películas; ¿Dónde un grupo de chicos hace una planificación increíble para llenarse los bolsillos de verde y terminar relajándose en algún lugar de las islas del Caribe? Bueno, ahora es el momento de brillar, ya que el juego Payday 2 trae de vuelta estos emocionantes y atrevidos escenarios a la industria del juego por segunda vez.','10000','20','0','https://cdn-products.eneba.com/resized-products/syNfttzWHZVGWkQ2QQGP4Oo5EcHIeleQ8GRjF2JcABs_350x200_1x-0.jpeg','1');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0003','Helldivers 2: La libertad, la paz y la democracia son los derechos fundamentales de la civilización nacida en la Supertierra, parte integral de su propia existencia. Sin embargo, a medida que la guerra continúa haciendo estragos, estos pilares se encuentran bajo una amenaza inminente. Es hora de que te unas a los Helldivers, la fuerza militar más formidable que la galaxia haya conocido jamás. Estás llamado a alistarte en esta unidad de élite y sumergirte en una trepidante, frenética y feroz aventura de disparos en tercera persona.','30000','35','0','https://cdn-products.eneba.com/resized-products/bXRUUblXKR-BlXnSIsUVR-jrJ1lnCSGA9qgbLh5L10Y_350x200_1x-0.jpg','1');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0004','Kingdom Come Deliverance : Compra la clave de Kingdom Come: Deliverance y entra en un mundo abierto basado en una historia ambientado en la época del Sacro Imperio Romano. El juego fue desarrollado por Warhorse Studios y es una pieza medieval realmente cruel. Experimenta la naturaleza de juego de rol del despiadado juego desde los primeros pasos que darás y lo sabes; No será un paseo por el parque.','8000','15','0','https://cdn-products.eneba.com/resized-products/XG-AI0DIQJ-oASonv4FeKEtcRTpD1AuBEV3LwXfA4xk_350x200_1x-0.jpeg','1');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0005','Dark Souls 3 : Dark Souls III key ofrece un RPG de acción oscuro y enrevesado de los desarrolladores FromSoftware. El fuego casi se ha extinguido, y allá donde el fuego muere viene la oscuridad que sumerge a la humanidad profunda en sí misma, ¿puedes mantener vivo el fuego? ¡Esta misión ha caído en tus incansables hombros!','26000','30','0','https://cdn-products.eneba.com/resized-products/BjdEY6u_350x200_1x-0.jpg','1');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0006','Devil May Cry 3 : Descubre el inquietante pasado de Dante en Devil May Cry 3, un juego que vuelve a sus raíces y te ve jugar como Dante, enfrentándote a peleas con monstruos que nunca antes habías visto, todo en el camino para enfrentarte a tu hermano gemelo, Virgil, en ¡Un enfrentamiento no tan fraternal!.','14000','20','0','https://cdn-products.eneba.com/resized-products/c6hilfrcme4sevplzc3d_350x200_1x-0.jpg','1');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0007','Dragon''s Dogma: Dark Arisen Steam key es un juego de rol de acción hack-and-slash desarrollado por Capcom. Dark Arisen es el relanzamiento y la expansión del juego original. Contiene todo el contenido del juego base, incluidos todos y cada uno de los DLC, junto con la nueva isla, nuevos monstruos, nuevas misiones, nuevas habilidades, equipo y mucho más. ¡Un sistema de combate lleno de acción que presenta varias criaturas míticas para desafiarte y te espera una experiencia gratificante! ¿Estás listo para participar en batallas legendarias contra los viciosos?.','7500','12','0','https://cdn-products.eneba.com/resized-products/hugudkvtebyy1lzbzjit_350x200_1x-0.jpg','2');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0008','Monster Hunter World : Es un juego de acción desarrollado por Capcom. En Monster Hunter World recorrás el Nuevo Mundo y explorarás su ecosistema y siempre serás consciente de las criaturas monstruosas con las que convives. Por ejemplo, una criatura parecida a wyvern llamada gran Jagra puede tragar su presa entera y es significativamente más fuerte una vez que ha comido, o Radobaan, una criatura con armadura que se irrita realmente si se le provoca, y Nergigante ... vas a preferir no encontrarte con él.','23000','15','0','https://cdn-products.eneba.com/resized-products/a4fbbfd448440942d3a787dc88a0c1cd_350x200_1x-0.jpg','2');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0009','¡Minecraft: Windows 10 edition :  permite unirte a la diversión en dispositivos que cuenten con el sistema operativo Windows 10!                                       Cuando hablamos de Minecraft, es dificil decidir dónde emepzar. El videojuego sandbox fue creado por Markus Persson y más tarde desarrollado por Mojang. Es reminiscente de un juego de 8-bits donde tu creatividad es el único factor limitante. Imagina jugar con Lego: es prácticamente lo mismo con Minecraft, sólo que los bloques con los que construir obras maestras son ilimitados.','19000','15','0','https://cdn-products.eneba.com/resized-products/mp6a3WpBEg3oX4iidlH8NYskzTrpcgj6aAFNe5BqbS0_350x200_1x-0.jpeg','2');
Insert into C##PRUEBA.MIAPP_PRODUCTO (CODIGO,DETALLE,PRECIO,STOCK,OFERTA,IMAGEN,TIPO) values ('0010','Assassin''s Creed: Odyssey es la undécima entrega importante de la serie Assassin Creed. Es un juego de rol de acción desarrollado por Ubisoft. En esta ocasión viaja a la Antigua Grecia, año 431 a.C., y sé testigo de la gran guerra ficticia entre sus ciudades-estado, Atenas y Esparta. ¡Toma parte en esta guerra como un mercenario despiadado y lucha por ambos bandos para unir a tu familia y disolver el culto que se ha extendido por toda Grecia!.','10000','20','0','https://cdn-products.eneba.com/resized-products/f9jvrf3nwdgdil287sla_350x200_1x-0.jpg','2');
--------------------------------------------------------
--  DDL for Index AUTH_GROU_GROUP_ID__0CD325B0_U
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PRUEBA"."AUTH_GROU_GROUP_ID__0CD325B0_U" ON "C##PRUEBA"."AUTH_GROUP_PERMISSIONS" ("GROUP_ID", "PERMISSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_PERM_CONTENT_T_01AB375A_U
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PRUEBA"."AUTH_PERM_CONTENT_T_01AB375A_U" ON "C##PRUEBA"."AUTH_PERMISSION" ("CONTENT_TYPE_ID", "CODENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_USER_USER_ID_G_94350C0C_U
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PRUEBA"."AUTH_USER_USER_ID_G_94350C0C_U" ON "C##PRUEBA"."AUTH_USER_GROUPS" ("USER_ID", "GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_USER_USER_ID_P_14A6B632_U
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PRUEBA"."AUTH_USER_USER_ID_P_14A6B632_U" ON "C##PRUEBA"."AUTH_USER_USER_PERMISSIONS" ("USER_ID", "PERMISSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DJANGO_CO_APP_LABEL_76BD3D3B_U
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PRUEBA"."DJANGO_CO_APP_LABEL_76BD3D3B_U" ON "C##PRUEBA"."DJANGO_CONTENT_TYPE" ("APP_LABEL", "MODEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_USER__USER_ID_6A12ED8B
--------------------------------------------------------

  CREATE INDEX "C##PRUEBA"."AUTH_USER__USER_ID_6A12ED8B" ON "C##PRUEBA"."AUTH_USER_GROUPS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_USER__PERMISSION_1FBB5F2C
--------------------------------------------------------

  CREATE INDEX "C##PRUEBA"."AUTH_USER__PERMISSION_1FBB5F2C" ON "C##PRUEBA"."AUTH_USER_USER_PERMISSIONS" ("PERMISSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MIAPP_MICU_USER_ID_BC3C0B7E
--------------------------------------------------------

  CREATE INDEX "C##PRUEBA"."MIAPP_MICU_USER_ID_BC3C0B7E" ON "C##PRUEBA"."MIAPP_MICUENTATF" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_PERMI_CONTENT_TY_2F476E4B
--------------------------------------------------------

  CREATE INDEX "C##PRUEBA"."AUTH_PERMI_CONTENT_TY_2F476E4B" ON "C##PRUEBA"."AUTH_PERMISSION" ("CONTENT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_USER__GROUP_ID_97559544
--------------------------------------------------------

  CREATE INDEX "C##PRUEBA"."AUTH_USER__GROUP_ID_97559544" ON "C##PRUEBA"."AUTH_USER_GROUPS" ("GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DJANGO_ADM_USER_ID_C564EBA6
--------------------------------------------------------

  CREATE INDEX "C##PRUEBA"."DJANGO_ADM_USER_ID_C564EBA6" ON "C##PRUEBA"."DJANGO_ADMIN_LOG" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_GROUP_GROUP_ID_B120CBF9
--------------------------------------------------------

  CREATE INDEX "C##PRUEBA"."AUTH_GROUP_GROUP_ID_B120CBF9" ON "C##PRUEBA"."AUTH_GROUP_PERMISSIONS" ("GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_USER__USER_ID_A95EAD1B
--------------------------------------------------------

  CREATE INDEX "C##PRUEBA"."AUTH_USER__USER_ID_A95EAD1B" ON "C##PRUEBA"."AUTH_USER_USER_PERMISSIONS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_GROUP_PERMISSION_84C5C92E
--------------------------------------------------------

  CREATE INDEX "C##PRUEBA"."AUTH_GROUP_PERMISSION_84C5C92E" ON "C##PRUEBA"."AUTH_GROUP_PERMISSIONS" ("PERMISSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DJANGO_ADM_CONTENT_TY_C4BCE8EB
--------------------------------------------------------

  CREATE INDEX "C##PRUEBA"."DJANGO_ADM_CONTENT_TY_C4BCE8EB" ON "C##PRUEBA"."DJANGO_ADMIN_LOG" ("CONTENT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DJANGO_SES_EXPIRE_DAT_A5C62663
--------------------------------------------------------

  CREATE INDEX "C##PRUEBA"."DJANGO_SES_EXPIRE_DAT_A5C62663" ON "C##PRUEBA"."DJANGO_SESSION" ("EXPIRE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table AUTH_GROUP
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."AUTH_GROUP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTH_GROUP" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PRUEBA"."AUTH_GROUP" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DJANGO_MIGRATIONS
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."DJANGO_MIGRATIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."DJANGO_MIGRATIONS" MODIFY ("APPLIED" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."DJANGO_MIGRATIONS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DJANGO_ADMIN_LOG
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."DJANGO_ADMIN_LOG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."DJANGO_ADMIN_LOG" MODIFY ("ACTION_TIME" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."DJANGO_ADMIN_LOG" MODIFY ("ACTION_FLAG" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."DJANGO_ADMIN_LOG" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."DJANGO_ADMIN_LOG" ADD CHECK ("ACTION_FLAG" >= 0) ENABLE;
  ALTER TABLE "C##PRUEBA"."DJANGO_ADMIN_LOG" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PRUEBA"."DJANGO_ADMIN_LOG" ADD CHECK ("ACTION_FLAG" >= 0) ENABLE;
--------------------------------------------------------
--  Constraints for Table MIAPP_MICUENTATF
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."MIAPP_MICUENTATF" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."MIAPP_MICUENTATF" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."MIAPP_MICUENTATF" MODIFY ("IMPORTANT" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."MIAPP_MICUENTATF" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."MIAPP_MICUENTATF" ADD CHECK ("IMPORTANT" IN (0,1)) ENABLE;
  ALTER TABLE "C##PRUEBA"."MIAPP_MICUENTATF" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PRUEBA"."MIAPP_MICUENTATF" ADD CHECK ("IMPORTANT" IN (0,1)) ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTH_GROUP_PERMISSIONS
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."AUTH_GROUP_PERMISSIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTH_GROUP_PERMISSIONS" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTH_GROUP_PERMISSIONS" MODIFY ("PERMISSION_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTH_GROUP_PERMISSIONS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PRUEBA"."AUTH_GROUP_PERMISSIONS" ADD CONSTRAINT "AUTH_GROU_GROUP_ID__0CD325B0_U" UNIQUE ("GROUP_ID", "PERMISSION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTH_USER_USER_PERMISSIONS
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."AUTH_USER_USER_PERMISSIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTH_USER_USER_PERMISSIONS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTH_USER_USER_PERMISSIONS" MODIFY ("PERMISSION_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTH_USER_USER_PERMISSIONS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PRUEBA"."AUTH_USER_USER_PERMISSIONS" ADD CONSTRAINT "AUTH_USER_USER_ID_P_14A6B632_U" UNIQUE ("USER_ID", "PERMISSION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTH_USER_GROUPS
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."AUTH_USER_GROUPS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTH_USER_GROUPS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTH_USER_GROUPS" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTH_USER_GROUPS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PRUEBA"."AUTH_USER_GROUPS" ADD CONSTRAINT "AUTH_USER_USER_ID_G_94350C0C_U" UNIQUE ("USER_ID", "GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DJANGO_SESSION
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."DJANGO_SESSION" MODIFY ("SESSION_KEY" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."DJANGO_SESSION" MODIFY ("EXPIRE_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."DJANGO_SESSION" ADD PRIMARY KEY ("SESSION_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTH_PERMISSION
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."AUTH_PERMISSION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTH_PERMISSION" MODIFY ("CONTENT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTH_PERMISSION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PRUEBA"."AUTH_PERMISSION" ADD CONSTRAINT "AUTH_PERM_CONTENT_T_01AB375A_U" UNIQUE ("CONTENT_TYPE_ID", "CODENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MIAPP_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."MIAPP_PRODUCTO" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."MIAPP_PRODUCTO" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."MIAPP_PRODUCTO" MODIFY ("STOCK" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."MIAPP_PRODUCTO" MODIFY ("OFERTA" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."MIAPP_PRODUCTO" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."MIAPP_PRODUCTO" ADD CHECK ("OFERTA" IN (0,1)) ENABLE;
  ALTER TABLE "C##PRUEBA"."MIAPP_PRODUCTO" ADD PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PRUEBA"."MIAPP_PRODUCTO" ADD CHECK ("OFERTA" IN (0,1)) ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTH_USER
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."AUTH_USER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTH_USER" MODIFY ("IS_SUPERUSER" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTH_USER" MODIFY ("IS_STAFF" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTH_USER" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTH_USER" MODIFY ("DATE_JOINED" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTH_USER" ADD CHECK ("IS_SUPERUSER" IN (0,1)) ENABLE;
  ALTER TABLE "C##PRUEBA"."AUTH_USER" ADD CHECK ("IS_STAFF" IN (0,1)) ENABLE;
  ALTER TABLE "C##PRUEBA"."AUTH_USER" ADD CHECK ("IS_ACTIVE" IN (0,1)) ENABLE;
  ALTER TABLE "C##PRUEBA"."AUTH_USER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PRUEBA"."AUTH_USER" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PRUEBA"."AUTH_USER" ADD CHECK ("IS_SUPERUSER" IN (0,1)) ENABLE;
  ALTER TABLE "C##PRUEBA"."AUTH_USER" ADD CHECK ("IS_STAFF" IN (0,1)) ENABLE;
  ALTER TABLE "C##PRUEBA"."AUTH_USER" ADD CHECK ("IS_ACTIVE" IN (0,1)) ENABLE;
--------------------------------------------------------
--  Constraints for Table DJANGO_CONTENT_TYPE
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."DJANGO_CONTENT_TYPE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."DJANGO_CONTENT_TYPE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PRUEBA"."DJANGO_CONTENT_TYPE" ADD CONSTRAINT "DJANGO_CO_APP_LABEL_76BD3D3B_U" UNIQUE ("APP_LABEL", "MODEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTHTOKEN_TOKEN
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."AUTHTOKEN_TOKEN" MODIFY ("KEY" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTHTOKEN_TOKEN" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTHTOKEN_TOKEN" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PRUEBA"."AUTHTOKEN_TOKEN" ADD PRIMARY KEY ("KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PRUEBA"."AUTHTOKEN_TOKEN" ADD UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTH_GROUP_PERMISSIONS
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."AUTH_GROUP_PERMISSIONS" ADD CONSTRAINT "AUTH_GROU_GROUP_ID_B120CBF9_F" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "C##PRUEBA"."AUTH_GROUP" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "C##PRUEBA"."AUTH_GROUP_PERMISSIONS" ADD CONSTRAINT "AUTH_GROU_PERMISSIO_84C5C92E_F" FOREIGN KEY ("PERMISSION_ID")
	  REFERENCES "C##PRUEBA"."AUTH_PERMISSION" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTH_PERMISSION
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."AUTH_PERMISSION" ADD CONSTRAINT "AUTH_PERM_CONTENT_T_2F476E4B_F" FOREIGN KEY ("CONTENT_TYPE_ID")
	  REFERENCES "C##PRUEBA"."DJANGO_CONTENT_TYPE" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTHTOKEN_TOKEN
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."AUTHTOKEN_TOKEN" ADD CONSTRAINT "AUTHTOKEN_USER_ID_35299EFF_F" FOREIGN KEY ("USER_ID")
	  REFERENCES "C##PRUEBA"."AUTH_USER" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTH_USER_GROUPS
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."AUTH_USER_GROUPS" ADD CONSTRAINT "AUTH_USER_USER_ID_6A12ED8B_F" FOREIGN KEY ("USER_ID")
	  REFERENCES "C##PRUEBA"."AUTH_USER" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "C##PRUEBA"."AUTH_USER_GROUPS" ADD CONSTRAINT "AUTH_USER_GROUP_ID_97559544_F" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "C##PRUEBA"."AUTH_GROUP" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTH_USER_USER_PERMISSIONS
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."AUTH_USER_USER_PERMISSIONS" ADD CONSTRAINT "AUTH_USER_USER_ID_A95EAD1B_F" FOREIGN KEY ("USER_ID")
	  REFERENCES "C##PRUEBA"."AUTH_USER" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "C##PRUEBA"."AUTH_USER_USER_PERMISSIONS" ADD CONSTRAINT "AUTH_USER_PERMISSIO_1FBB5F2C_F" FOREIGN KEY ("PERMISSION_ID")
	  REFERENCES "C##PRUEBA"."AUTH_PERMISSION" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DJANGO_ADMIN_LOG
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."DJANGO_ADMIN_LOG" ADD CONSTRAINT "DJANGO_AD_CONTENT_T_C4BCE8EB_F" FOREIGN KEY ("CONTENT_TYPE_ID")
	  REFERENCES "C##PRUEBA"."DJANGO_CONTENT_TYPE" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "C##PRUEBA"."DJANGO_ADMIN_LOG" ADD CONSTRAINT "DJANGO_AD_USER_ID_C564EBA6_F" FOREIGN KEY ("USER_ID")
	  REFERENCES "C##PRUEBA"."AUTH_USER" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MIAPP_MICUENTATF
--------------------------------------------------------

  ALTER TABLE "C##PRUEBA"."MIAPP_MICUENTATF" ADD CONSTRAINT "MIAPP_MIC_USER_ID_BC3C0B7E_F" FOREIGN KEY ("USER_ID")
	  REFERENCES "C##PRUEBA"."AUTH_USER" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
